# $Id: Makefile,v 1.8 2008-10-16 18:04:01 roystgnr Exp $

# The location of the mesh library
#LIBMESH_DIR = /workspace/vikram/libmesh_build_master_normal
LIBMESH_DIR = /home/vikram/libmesh_build_master_normal

# include the library options determined by configure
include $(LIBMESH_DIR)/Make.common

target 	   := ./scalar_field_breakdown-$(METHOD)

# include my common application options
include Make_template
