function B = getB(xFE)
%goes with becker_vexler_stretch6_adj

nElem = length(xFE)-1;
B = zeros(nElem-1,5);
for ii = 1:nElem-1
    xim1 = xFE(ii);
    xi = xFE(ii+1);
    xip1 = xFE(ii+2);
    
    %left side of hat
    al = 1/(xi-xim1);
    bl = -xim1/(xi-xim1);
    x1 = xim1; x2 = xi;
    B(ii,1) = 0.5*(x2-x1); %phi(x) = 1;
    B(ii,2) = (al*sin(2*pi*x2)-2*pi*(al*x2+bl)*cos(2*pi*x2) ...
        -(al*sin(2*pi*x1)-2*pi*(al*x1+bl)*cos(2*pi*x1))) ...
        /(4*pi^2); %phi(x) = sin(2*pi*x)
    B(ii,3) = (al*cos(2*pi*x2)+2*pi*(al*x2+bl)*sin(2*pi*x2) ...
        -(al*cos(2*pi*x1)+2*pi*(al*x1+bl)*sin(2*pi*x1))) ...
        /(4*pi^2); %phi(x) = cos(2*pi*x)
    B(ii,4) = (al*sin(4*pi*x2)-4*pi*(al*x2+bl)*cos(4*pi*x2) ...
        -(al*sin(4*pi*x1)-4*pi*(al*x1+bl)*cos(4*pi*x1))) ...
        /(16*pi^2); %phi(x) = sin(4*pi*x)
    B(ii,5) = (al*cos(4*pi*x2)+4*pi*(al*x2+bl)*sin(4*pi*x2) ...
        -(al*cos(4*pi*x1)+4*pi*(al*x1+bl)*sin(4*pi*x1))) ...
        /(16*pi^2); %phi(x) = cos(4*pi*x)
    
    %right side of hat
    ar = -1/(xip1-xi);
    br = xip1/(xip1-xi);
    x1 = xi; x2 = xip1;
    B(ii,1) = B(ii,1) + 0.5*(x2-x1); %phi(x) = 1;
    B(ii,2) = B(ii,2) + (ar*sin(2*pi*x2)-2*pi*(ar*x2+br)*cos(2*pi*x2) ...
        -(ar*sin(2*pi*x1)-2*pi*(ar*x1+br)*cos(2*pi*x1))) ...
        /(4*pi^2); %phi(x) = sin(2*pi*x)
    B(ii,3) = B(ii,3) + (ar*cos(2*pi*x2)+2*pi*(ar*x2+br)*sin(2*pi*x2) ...
        -(ar*cos(2*pi*x1)+2*pi*(ar*x1+br)*sin(2*pi*x1))) ...
        /(4*pi^2); %phi(x) = cos(2*pi*x)
    B(ii,4) = B(ii,4) + (ar*sin(4*pi*x2)-4*pi*(ar*x2+br)*cos(4*pi*x2) ...
        -(ar*sin(4*pi*x1)-4*pi*(ar*x1+br)*cos(4*pi*x1))) ...
        /(16*pi^2); %phi(x) = sin(4*pi*x)
    B(ii,5) = B(ii,5) + (ar*cos(4*pi*x2)+4*pi*(ar*x2+br)*sin(4*pi*x2) ...
        -(ar*cos(4*pi*x1)+4*pi*(ar*x1+br)*sin(4*pi*x1))) ...
        /(16*pi^2); %phi(x) = cos(4*pi*x)
end
B = -B;